export const projects = [
  {
    id: 1,
    title: "JARVIS-2: Privacy-First Multi-Agent Home Automation Assistant",
    shortDescription: "A privacy-first, multi-agent assistant that runs locally and shows its reasoning before it acts",
    fullDescription: "JARVIS-2 is a privacy-first multi-agent assistant I have been designing since October 2024, now in early development. The goal is a local-first platform that controls smart-home devices and handles everyday workflows while showing its reasoning before it acts. The planned architecture uses a LangGraph supervisor to coordinate seven specialized agents (speech, Home Assistant, weather, media, calendar, memory and scheduler) through typed adapters, with approval gates for anything risky and OpenTelemetry tracing across the system. It is built around local inference: Whisper for speech-to-text and Piper for text-to-speech via Home Assistant and ESPHome, with the MCP protocol for portable tool connectors and Docker Compose or Kubernetes for deployment. Security is handled with per-agent RBAC, container isolation and AES-256 encrypted storage. The project has gone through more than ten iterations and is currently at the architecture and early-implementation stage, not yet ready for production use.",
    techStack: ["Python 3.10+", "LangGraph", "OpenTelemetry", "Docker Compose", "Home Assistant", "Whisper STT", "Piper TTS", "MCP Protocol", "ESPHome", "DuckDB", "SQLite", "Kubernetes", "RBAC", "AES-256"],
    category: "AI/ML" as const,
    github: "https://github.com/abdulsalam-aldabik/jarvis-ai",
    featured: true,
    duration: "October 2024 - Ongoing (Early Development Phase)",
    teamSize: "Solo (Technical Architect, Lead Engineer, Platform & Security Architect)",
    metrics: [
      { label: "Design Iterations", value: 10, suffix: "+" },
      { label: "Planned Agents", value: 7, suffix: "+" },
      { label: "Phase", value: 1, suffix: "" },
    ],
    challenges: [
      "Most assistants make decisions you can't inspect. I'm designing a stateful LangGraph supervisor that previews its plan with rationale and risk tags, and waits for human approval before running anything, with full tracing at each step.",
      "Cloud voice assistants send audio off-device. I'm integrating local Whisper speech-to-text and Piper text-to-speech with Home Assistant and ESPHome satellites so wake-word detection and commands run on-device.",
      "Adding a capability usually means editing the orchestrator. I'm using manifest-based registration (YAML plus Python) with typed MCP schemas so new agents drop in without touching the core, each with its own RBAC scope.",
      "Persistent telemetry and forced cloud access break privacy. I'm scoping RBAC per agent, isolating containers with seccomp and a read-only filesystem, gating cloud access behind explicit approval, and encrypting local storage with key rotation.",
      "Automated flows are hard to audit. I'm instrumenting every agent and tool boundary with OpenTelemetry traces, metrics and logs, plus correlation IDs and immutable audit trails for compliance (SOC 2 and GDPR-ready).",
    ],
  },
  {
    id: 2,
    title: "Autonomous Driving AI System",
    shortDescription: "A deep-learning self-driving system for the Assetto Corsa racing simulator",
    fullDescription: "I built a self-driving system for Assetto Corsa that turns camera frames into continuous steering using a regression model. The pipeline covers everything from data collection to real-time control: ResNet50 predicts the steering angle, and YOLOv11 with OCR reads traffic signs and speed limits.",
    techStack: ["Python", "ResNet50", "YOLOv11", "OCR", "Deep Learning", "Computer Vision", "Real-time Control"],
    category: "AI/ML" as const,
    github: "https://github.com/abdulsalam-aldabik/SelfDriving",
    image: "/projects/autonomous-car.jpg",
    photos: ["/projects/autonomous-car.jpg"],
    featured: true,
    duration: "Machine Learning Project - Thomas More",
    teamSize: "2 members",
    metrics: [
      { label: "Systems", value: 2, suffix: "" },
      { label: "Models", value: 2, suffix: "" },
      { label: "Real-time", value: 1, suffix: "" },
    ],
    challenges: [
      "Capturing and balancing the steering data so the model learned evenly",
      "Predicting accurate steering on sharp turns",
      "Wiring real-time control to a virtual Xbox controller",
      "Running the driving and sign-detection systems side by side",
    ],
    outcomes: [
      "Predicted steering angles straight from camera frames with ResNet50 regression",
      "Held the line through sharp turns and recovered after drifting off-line",
      "Read speed limits automatically with YOLOv11 sign detection and OCR",
      "Adjusted throttle in real time through keyboard input",
      "Ran a full driving demo with detection working alongside it",
    ],
    demo: "https://youtu.be/f1ZEafmHv8c",
  },
  {
    id: 3,
    title: "Requirements Analysis",
    shortDescription: "A team requirements-analysis project for a website build",
    fullDescription: "I led a team of five to produce a data model, a use-case diagram and prototype screens in Axure. As group manager I ran the process end to end and kept everyone aligned on scope and deadlines.",
    techStack: ["Axure", "Data Modeling", "Use Case Diagrams"],
    category: "Full Stack" as const,
    github: "",
    image: "/projects/requirements-analysis.jpg",
    featured: true,
    duration: "Second year project",
    teamSize: "5 members",
    metrics: [
      { label: "Team Size", value: 5, suffix: "" },
      { label: "Deliverables", value: 3, suffix: "" },
    ],
    challenges: [
      "Leading a team of five",
      "Building a complete data model",
      "Designing the prototype screens",
    ],
    outcomes: [
      "Delivered a full requirements analysis",
      "Produced the data model, use-case diagram and prototype screens",
      "Kept the team coordinated as group manager",
    ],
  },
  {
    id: 4,
    title: "Home Assistant Smart Home System",
    shortDescription: "A privacy-focused smart-home system with local voice control on virtualized infrastructure",
    fullDescription: "I designed and built a privacy-focused smart-home system on Home Assistant OS, running in a KVM virtual machine on Ubuntu Server. It handles multi-room voice control through an ESP32 Wyoming satellite that processes speech locally, a custom Lovelace dashboard on a dedicated touchscreen, and 5.1 surround-sound integration. Everything runs on-device with no cloud dependency. The setup covers room-based automations, energy monitoring, climate control and custom scripts for more involved workflows.",
    techStack: ["Home Assistant OS", "KVM/QEMU", "Ubuntu Server", "ESP32", "Wyoming Satellite", "Raspberry Pi 4", "Lovelace UI", "Voice Control", "Bridge Networking"],
    category: "IoT" as const,
    github: "",
    image: "/projects/smart-home.jpg",
    featured: true,
    duration: "2019-ongoing",
    teamSize: "Solo",
    metrics: [
      { label: "Rooms", value: 3, suffix: "+" },
      { label: "Duration", value: 6, suffix: " years" },
      { label: "Uptime", value: 99, suffix: "%" },
    ],
    challenges: [
      "Tuned the KVM virtual machine with CPU pinning and dedicated resources so automation stayed responsive",
      "Set up an ESP32 as a Wyoming satellite for local speech recognition, with no cloud",
      "Routed the PC's 5.1 sound system through Home Assistant for whole-home audio",
      "Configured bridge networking so the VM talks directly to devices on the local network",
    ],
    outcomes: [
      "A working privacy-focused smart home with local voice control",
      "Voice processed on-device, without Google or Alexa",
      "Reliable automation reachable by touchscreen, voice and mobile app",
      "A virtualized base I can keep expanding",
    ],
  },
  {
    id: 5,
    title: "Rasbee",
    shortDescription: "Beehive environment monitoring system",
    fullDescription: "A team project using an ESP32 and Raspberry Pi 4 to monitor a beehive's temperature, humidity and light, and to control the lights. The ESP32 collects readings and sends them to the Raspberry Pi over Bluetooth Low Energy, which then pushes notifications to a phone and to Ubeac.",
    techStack: ["ESP32", "Raspberry Pi 4", "BLE", "Ubeac", "Mobile Notifications"],
    category: "IoT" as const,
    github: "",
    image: "/projects/rasbee.jpg",
    featured: false,
    duration: "Recent project",
    teamSize: "Collaboration",
    metrics: [
      { label: "Sensors", value: 3, suffix: "" },
      { label: "Devices", value: 2, suffix: "" },
    ],
    challenges: [
      "Linking the ESP32 and Raspberry Pi over BLE",
      "Monitoring several environmental readings at once",
      "Sending notifications in real time",
    ],
    outcomes: [
      "Tracked temperature, humidity and light reliably",
      "Controlled the lights based on conditions",
      "Sent live notifications to a phone and to Ubeac",
    ],
  },
  {
    id: 6,
    title: "Smart Home Control - Flutter Mobile App",
    shortDescription: "Flutter mobile app for smart home device control and server monitoring",
    fullDescription: "I built a Flutter/Dart mobile app to manage my smart home from a phone. It controls devices grouped into custom sections, shows a live dashboard of device states and sensor data, and can start and stop Docker containers remotely. It also reports basic server stats and resource use, giving one place to manage both Home Assistant devices and the Ubuntu Server behind them.",
    techStack: ["Flutter", "Dart", "Home Assistant API", "Docker API", "REST API", "Mobile Development", "Android"],
    category: "Full Stack" as const,
    github: "",
    featured: true,
    duration: "2025",
    teamSize: "Solo",
    metrics: [
      { label: "Platforms", value: 1, suffix: "" },
      { label: "Features", value: 3, suffix: "" },
      { label: "Devices Controlled", value: 10, suffix: "+" },
    ],
    challenges: [
      "Integrating the Home Assistant API for device control and state",
      "Talking to the Docker API for remote container management",
      "Designing a clear UI for grouping devices and reading the dashboard",
      "Keeping device and server data updating in real time",
    ],
    outcomes: [
      "A working mobile app to control the smart home on the go",
      "A device-grouping system for tidy management",
      "A live dashboard of device states and sensor data",
      "Docker start/stop control with basic server monitoring",
    ],
  },
  {
    id: 7,
    title: "Ubuntu Server Infrastructure",
    shortDescription: "A home server running virtualization, containers and secure remote access",
    fullDescription: "I built and maintain a home server on Ubuntu Server that acts as a hub for virtualization (KVM/QEMU), containers (Docker), networking and remote access. libvirt handles the VM lifecycle with isolated virtual networks and resource limits. The network runs on gigabit Ethernet with a static IP, UFW firewall rules and NordVPN Meshnet for secure remote admin. Samba and NFS provide central file storage at 192.168.0.116. It hosts several VMs and containerized services at over 99% uptime, including Home Assistant, Jellyfin and various development environments.",
    techStack: ["Ubuntu Server", "KVM/QEMU", "libvirt", "Docker Engine", "Docker Compose", "NordVPN Meshnet", "Samba/NFS", "UFW Firewall", "htop", "systemd"],
    category: "DevOps" as const,
    github: "",
    featured: true,
    duration: "2019-ongoing",
    teamSize: "Solo",
    metrics: [
      { label: "Uptime", value: 99, suffix: "%" },
      { label: "VMs Hosted", value: 3, suffix: "+" },
      { label: "Services", value: 10, suffix: "+" },
    ],
    challenges: [
      "Tracked down memory exhaustion with top and htop and set proper resource limits",
      "Fixed slow transfers (2 MB/s) caused by a USB Ethernet adapter and reached full gigabit speeds",
      "Reconfigured the NordVPN CLI auth after a password change to keep remote access working",
      "Resolved Docker bind-mount permission conflicts affecting deployments",
    ],
    outcomes: [
      "A stable home-server setup at over 99% uptime",
      "Several VMs and containers running at once",
      "Secure remote access from anywhere over VPN Meshnet",
      "A base I can scale for future projects",
    ],
  },
  {
    id: 8,
    title: "Jellyfin Home Media Server",
    shortDescription: "Self-hosted media streaming platform with Docker containerization",
    fullDescription: "I deployed a self-hosted Jellyfin media server in Docker on Ubuntu Server as a free alternative to paid streaming, with full control over the library. A Docker Compose stack handles container management and updates, with volume mounts for movies, TV, music and ebooks. I set up network file sharing for central storage and tuned transcoding for different devices and bandwidth, plus user accounts and access control for secure streaming at home and remotely.",
    techStack: ["Jellyfin", "Docker", "Docker Compose", "Ubuntu Server", "FFmpeg", "Network Storage", "Media Transcoding"],
    category: "DevOps" as const,
    github: "",
    featured: false,
    duration: "2023-ongoing",
    teamSize: "Solo",
    metrics: [
      { label: "Users", value: 5, suffix: "+" },
      { label: "Media Libraries", value: 4, suffix: "" },
      { label: "Devices", value: 10, suffix: "+" },
    ],
    challenges: [
      "Diagnosed and fixed corrupted XML metadata that blocked playback, and added validation and backups",
      "Fixed DirectoryNotFoundException errors by mapping host paths to container volumes correctly so FFmpeg could read the files",
      "Sorted out Docker bind-mount permissions for read/write access to media",
    ],
    outcomes: [
      "A working media server reachable at home and remotely",
      "Reliable streaming for several users at once",
      "Automatic library management and metadata fetching",
      "A free alternative to subscription streaming",
    ],
  },
  {
    id: 9,
    title: "Tour de France Dashboard",
    shortDescription: "Comprehensive BI analytics using Qlik Sense with dimensional modeling",
    fullDescription: "I built a business-intelligence dashboard in Qlik Sense Cloud analysing over 100 years of Tour de France data. The data model follows Kimball dimensional modelling with a star schema: a fact table of Tour editions and dimensions for riders, countries, teams and stages. I wrote the ETL in Qlik load scripts to clean, validate and transform the data, and added calculated fields for time conversions, rankings and aggregations. The dashboards answer questions about historical trends, dominant riders, country performance, stage distribution and winner demographics. Along the way I resolved circular references, synthetic keys and field-mapping errors through cleaner modelling.",
    techStack: ["Qlik Sense Cloud", "Kimball Methodology", "Star Schema", "ETL", "Data Modeling", "Qlik Script", "Data Visualization", "BI Analytics"],
    category: "Data Science" as const,
    github: "",
    image: "/projects/tour-de-france.jpg",
    photos: ["/projects/tour-de-france.jpg"],
    featured: false,
    duration: "Business Intelligence Project - Thomas More",
    teamSize: "Solo",
    metrics: [
      { label: "Data Years", value: 100, suffix: "+" },
      { label: "Dashboard Sheets", value: 5, suffix: "+" },
      { label: "Visualizations", value: 15, suffix: "+" },
    ],
    challenges: [
      "Resolved circular references by restructuring joins and key fields",
      "Removed synthetic keys with proper dimensional modelling and unique keys",
      "Parsed race durations from formats like 1h 42' 54\" into seconds",
      "Handled missing values, outliers and inconsistent historical data",
    ],
    outcomes: [
      "A star-schema model following BI best practice",
      "Interactive dashboards answering real analytical questions",
      "Solid ETL, transformation and Qlik Sense work end to end",
      "An exam-ready project meeting all the criteria",
    ],
  },
];

export const skills = {
  aiml: ["LangGraph", "Multi-Agent Systems", "FastAI", "PyTorch", "TensorFlow", "YOLO", "Computer Vision", "Deep Learning", "AI", "Machine Learning", "Whisper STT", "NLP"],
  programming: ["Python 3.10+", "Java", "C++", "JavaScript", "TypeScript", "SQL", "Dart", "Flutter"],
  webDev: ["React", "Next.js", "ASP.NET", "Spring Boot", "Tailwind CSS", "HTML/CSS", "Axure", "Data Modeling", "REST API"],
  devops: ["Docker", "Docker Compose", "Kubernetes", "OpenTelemetry", "CI/CD", "Helm Charts", "Ubuntu Server", "Git", "GitHub", "KVM/QEMU", "libvirt", "NordVPN", "UFW Firewall"],
  hardware: ["Raspberry Pi 4", "ESP32", "Home Assistant OS", "ESPHome", "Arduino", "BLE", "IoT Systems", "Wyoming Satellite"],
  dataScience: ["Qlik Sense", "ETL", "Dimensional Modeling", "Star Schema", "Kimball Methodology", "Data Visualization", "BI Analytics"],
  media: ["Jellyfin", "FFmpeg", "Media Transcoding", "Samba/NFS"],
  security: ["Container Isolation", "Policy Enforcement", "Audit Logging", "Secrets Management", "VPN", "Firewall Configuration"]
};

export const personalInfo = {
  name: "Abdul salam Aldabik",
  nickname: "Salumi",
  title: "Applied Computer Science Student - AI Specialization",
  tagline: "I build AI and IoT systems that run locally and respect privacy",
  bio: "I'm an Applied Computer Science student specializing in AI at Thomas More. I like building real systems, from computer-vision models to self-hosted infrastructure, and I work well in teams, usually as the person mapping the architecture and keeping things moving.",
  location: "Av. d'Auderghem 275, 1040 Etterbeek, Belgium",
  university: "Thomas More",
  program: "Applied Computer Science - AI Specialization",
  email: "r0918747@student.thomasmore.be",
  phone: "0032465726743",
  github: "https://github.com/abdulsalam-aldabik",
  linkedin: "https://www.linkedin.com/in/abdulsalamaldabik/"
};
